; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30031.0 

	TITLE	A:\CPP\05_CONCURRENT\ONLINE\SECTION04\reorder1.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?a@@3HA						; a
PUBLIC	?b@@3HA						; b
_BSS	SEGMENT
?a@@3HA	DD	01H DUP (?)				; a
?b@@3HA	DD	01H DUP (?)				; b
_BSS	ENDS
PUBLIC	?foo@@YAXXZ					; foo
PUBLIC	?goo@@YAXXZ					; goo
; Function compile flags: /Ogtpy
; File A:\CPP\05_CONCURRENT\ONLINE\SECTION04\reorder1.cpp
;	COMDAT ?goo@@YAXXZ
_TEXT	SEGMENT
?goo@@YAXXZ PROC					; goo, COMDAT

; 19   :     if ( b == 1 )
; 20   :     {
; 21   :         // a == 1 을 보장할수 있을까 ?
; 22   :     }
; 23   : }

	ret	0
?goo@@YAXXZ ENDP					; goo
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File A:\CPP\05_CONCURRENT\ONLINE\SECTION04\reorder1.cpp
;	COMDAT ?foo@@YAXXZ
_TEXT	SEGMENT
?foo@@YAXXZ PROC					; foo, COMDAT

; 10   :     a = b + 1;

	mov	eax, DWORD PTR ?b@@3HA			; b
	inc	eax
	mov	DWORD PTR ?a@@3HA, eax			; a

; 11   :     //----- fence -----------
; 12   :     __asm { mfence }

	mfence

; 13   :     b = 1;

	mov	DWORD PTR ?b@@3HA, 1			; b

; 14   : }

	ret	0
?foo@@YAXXZ ENDP					; foo
_TEXT	ENDS
END
